Locales['hr'] = {
  -- Svlačionica
  ['cloakroom'] = 'Svlačionica | 👒',
  ['citizen_wear'] = 'Civilno Odelo | 👨',
  ['mafia_wear'] = 'Mafijaška Uniforma | 🎩',
  ['no_outfit'] = 'Ne postoji uniforma koja vam odgovara!',
  ['open_cloackroom'] = 'Pritisnite ~INPUT_CONTEXT~ da promijenite odeću.',
  -- Oružarnica
  ['remove_object'] = 'Uzmi predmet | 📷',
  ['deposit_object'] = 'Ostavi predmet| 📷',
  ['buy_weapon'] = 'Kupi oružje | 🔫',
  ['get_weapon'] = 'Uzmi oružje | 🔫',
  ['put_weapon'] = 'Ostavi oružje | 🔫',
  ['buy_weapons'] = 'Kupi oružje | 💵',
  ['armory'] = 'Oružarnica | ⚙️',
  ['open_armory'] = 'Pritisnite ~INPUT_CONTEXT~ da pristupite oružarnici.',
  ['armory_owned'] = 'Već Imate ✅',
  ['armory_free'] = 'Besplatno',
  ['armory_item'] = '%s€',
  ['armory_weapontitle'] = 'Oružarnica | ⚙️ ➥ Kupi oružje',
  ['armory_componenttitle'] = 'Dodatci za oružje | ⚙️',
  ['armory_bought'] = 'Kupili ste %s za %s€',
  ['armory_money'] = 'Nemate dovoljno novca za ovo oruŽje',
  ['armory_hascomponent'] = 'Već imate taj dodatak!',
  ['get_weapon_menu'] = 'Oružarnica | ⚙️ ➥ Uzmi oružje',
  ['put_weapon_menu'] = 'Oružarnica | ⚙️ ➥ Ostavi oružje',
  -- Garaža
  ['vehicle_menu'] = 'Vozila',
  ['vehicle_blocked'] = 'Spawn pointi su blokirani!',
  ['garage_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da izaberete vozilo.',
  ['garage_title'] = 'Izaberi Vozilo | 🚗',
  ['garage_stored'] = 'Parkirano ✅',
  ['garage_notstored'] = 'Van Garaže ❌',
  ['garage_storing'] = 'Pokušavamo da uklonimo vozilo, budite sigurni da nema igrača oko njega.',
  ['garage_has_stored'] = 'Vozilo je parkirano u garazu',
  ['garage_has_notstored'] = 'U blizini nema vozila',
  ['garage_notavailable'] = 'Vaše vozilo nije parkirano.',
  ['garage_blocked'] = 'Nema slobodnih spawn pointa!',
  ['garage_empty'] = 'Nemate vozilo u garazi.',
  ['garage_released'] = 'Vaše vozilo je izparkirano iz garaze.',
  ['garage_store_nearby'] = 'U blizini nema vozila.',
  ['garage_storeditem'] = 'Izaberite Vozilo | 🚗',
  ['garage_storeitem'] = 'Parkirajte Vozilo | 🚗',
  ['garage_buyitem'] = 'Kupite Vozilo | 🚗',
  ['helicopter_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da pristupiš radnjama sa helikopterom.',
  ['helicopter_notauthorized'] = 'Niste ovlašteni da kupite helikopter.',
  ['shop_item'] = '%s€',
  ['vehicleshop_title'] = 'Kupite Vozilo | 🚗',
  ['vehicleshop_confirm'] = 'Želite li kupiti ovo vozilo?',
  ['vehicleshop_bought'] = 'Kupili ste %s za $%s',
  ['vehicleshop_money'] = 'Nemate dovoljno novca',
  ['vehicleshop_awaiting_model'] = 'Vozilo se trenutno PREUZIMA & UČITAVA molimo vas sacekajte',
  ['confirm_no'] = 'Ne ❌',
  ['confirm_yes'] = 'Da ✅',
  -- Radnje
  ['citizen_interaction'] = 'Upravljaj ljudima | 👨',
  ['vehicle_interaction'] = 'Upravljaj vozilom | 🚗',
  ['object_spawner'] = 'Stvaraj Predmete | 👜',

  ['id_card'] = 'Licna karta | 💳',
  ['search'] = 'Pretraži | 🔍',
  ['handcuff'] = 'Zaveži / Odveži | ⛓️',
  ['drag'] = 'Vuci | 👨',
  ['put_in_vehicle'] = 'Stavi u vozilo | 🚗',
  ['out_the_vehicle'] = 'Izvuci iz vozila | 🚗',
  ['no_players_nearby'] = 'Nema igraca u blizini!',
  ['being_searched'] = 'Vi ste pretraženi od strane mafije',
  -- Vehicle interaction
  ['vehicle_info'] = 'Informacije o vozilu | 🚗',
  ['pick_lock'] = 'Obij vozilo | 🔓',
  ['vehicle_unlocked'] = 'Vozilo uspješno Otkljucano',
  ['no_vehicles_nearby'] = 'U blizini nema vozila',
  ['search_database'] = 'Pretraga po registarskom broju | 🚗',
  ['search_database_title'] = 'Informacije - pretražite registrarske brojeve',
  ['search_database_error_invalid'] = 'To nije validan registarski broj',
  ['search_database_error_not_found'] = 'Ova registracija nije ni na jednom vozilu!',
  ['search_database_found'] = 'Vozilo je registrovano na %s',
  -- Traffic interaction
  ['traffic_interaction'] = 'Upravljanje saobraćajem | 🚦',
  ['cone'] = 'Čunj | 🛑',
  ['barrier'] = 'Granica | 🚧',
  ['spikestrips'] = 'Bodlje | ⛏️',
  ['box'] = 'Kutija | 📦',
  ['cash'] = 'Novac | 💵',
  -- ID Card Menu
  ['name'] = 'Ime: %s',
  ['job'] = 'Posao: %s',
  ['sex'] = 'Spol: %s',
  ['dob'] = 'Dob: %s',
  ['height'] = 'Visina: %s',
  ['id'] = 'Indetifikacija: %s',
  ['bac'] = 'BAC: %s',
  ['unknown'] = 'nepoznato',
  ['male'] = 'Muško',
  ['female'] = 'Žensko',
  -- Body Search Menu
  ['guns_label'] = '--- Oružja ---',
  ['inventory_label'] = '--- Inventar ---',
  ['license_label'] = ' --- Dozvole ---',
  ['confiscate'] = 'Oduzmi %s',
  ['confiscate_weapon'] = 'Oduzmi %s sa %s metkovima',
  ['confiscate_inv'] = 'Oduzmi %sx %s',
  ['confiscate_dirty'] = 'Oduzmi prljav novac: <span style="color:red;">%s€</span>',
  ['you_confiscated'] = 'Oduzeli ste %sx %s od %s',
  ['got_confiscated'] = '%sx %s uzeto od strane %s',
  ['you_confiscated_account'] = 'Oduzeli ste %s€ (%s) od %s',
  ['got_confiscated_account'] = '%s€ (%s) oduzeta od %s',
  ['you_confiscated_weapon'] = 'Oduzeli ste %s od %s sa ~o~%s metkova',
  ['got_confiscated_weapon'] = 'Tvoj %s sa ~o~%s metkova je oduzet od strane %s',
  -- Vehicle Info Menu
  ['plate'] = 'Tablice ➥ %s',
  ['owner_unknown'] = 'Vlasnik ➥ Nepoznat',
  ['owner'] = 'Vlasnik ➥ %s',
  -- Boss Menu
  ['open_bossmenu'] = 'Pritisnite ~INPUT_CONTEXT~ da otvorite meni',
  ['quantity_invalid'] = 'Nevazeća kolicina',
  ['have_withdrawn'] = 'Podigli ste %sx %s',
  ['have_deposited'] = 'Ostavili ste %sx %s',
  ['quantity'] = 'Kolicina',
  ['inventory'] = 'Inventar',
  ['mafia_stock'] = 'Mafijaške zalihe',
  -- Misc
  ['remove_prop'] = 'Pritisnite ~INPUT_CONTEXT~ da obrišete objekat.',
  ['map_blip'] = 'Mafija',
  ['unrestrained_timer'] = 'Lisice vam se polako olabavljaju i spadaju sa ruku.',
}
